### ISSUE TITLE
Provide typescript declaration for your module

### ISSUE THREAD

**Issue by Edward-Roshan** [silverwind/rrdir#6]
There is no any type define for typescript in type search. please make definitely type or let me do your favor?

**Comment by Edward-Roshan** [comment]
I helped you to write definitely typed package. PR is here: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/49448

Anyone use your module with typescript would be probably to use "@types/rrdir" to get type definitions. No thanks, Buddy. although you don't want to say anything.

**Comment by silverwind** [comment]
Contributions in the form of a static `index.d.ts` welcome. I don't personally care about TypeScript, thought.

**Comment by Edward-Roshan** [comment]
No need for double work for me. here is published types: https://www.npmjs.com/package/@types/rrdir
Thanks for your contribution to the open-source community.
